# generated by datamodel-codegen:
#   filename:  algo-feed.schema.json

from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, Field, RootModel, conint


class AlgoEvent1(BaseModel):
    algo_id: Optional[str] = None
    data: Optional[Any] = None
    message: Optional[str] = None
    symbol: Optional[str] = None
    tag: str
    timestamp: str
    type: Literal['ALGO_CUSTOM']


class AlgoEvent(RootModel[AlgoEvent1]):
    root: AlgoEvent1 = Field(
        ...,
        description='Tagged by the JSON `"type"` field. Only `ALGO_CUSTOM` is defined; any other (or unknown) type fails deserialization — the server logs it at `debug` and continues.',
    )


class TapeEvent(BaseModel):
    buy_pct_5m: Optional[float] = Field(
        None,
        description='5-minute aggressive-buy share (0–100). Present only on `market_summary`.',
    )
    close_price: Optional[float] = None
    cvd: Optional[float] = Field(
        None, description='Session cumulative volume delta at event time.'
    )
    event: Literal[
        'new_high', 'new_low', 'new_high_and_low', 'price_update', 'market_summary'
    ] = Field(
        ...,
        description='Which transition triggered this `TapeEvent`.\n\n- `price_update`: intraday last-price update for symbols requested by algo clients via `ALGO_WEB_WATCH` (stop/target tracking). - `market_summary`: periodic market push-pull + breadth bar, emitted only while a client is subscribed via `ALGO_WEB_SUMMARY`.',
    )
    high_count: conint(ge=0) = Field(
        ..., description='Per-symbol cumulative new-high count this session.'
    )
    is_week52_high: bool
    is_week52_low: bool
    last_price: Optional[float] = None
    last_size: Optional[float] = Field(
        None, description='Size of the classified print at event time.'
    )
    low_count: conint(ge=0) = Field(
        ..., description='Per-symbol cumulative new-low count this session.'
    )
    market_high_rate_1m: conint(ge=0) = Field(
        ..., description='Market-wide rolling rate — highs in last 60 s.'
    )
    market_high_rate_20m: Optional[conint(ge=0)] = Field(
        0, description='Market-wide rolling rate — highs in last 20 m.'
    )
    market_high_rate_30s: conint(ge=0) = Field(
        ..., description='Market-wide rolling rate — highs in last 30 s.'
    )
    market_high_rate_5m: Optional[conint(ge=0)] = Field(
        0, description='Market-wide rolling rate — highs in last 5 m.'
    )
    market_low_rate_1m: conint(ge=0) = Field(
        ..., description='Market-wide rolling rate — lows in last 60 s.'
    )
    market_low_rate_20m: Optional[conint(ge=0)] = Field(
        0, description='Market-wide rolling rate — lows in last 20 m.'
    )
    market_low_rate_30s: conint(ge=0) = Field(
        ..., description='Market-wide rolling rate — lows in last 30 s.'
    )
    market_low_rate_5m: Optional[conint(ge=0)] = Field(
        0, description='Market-wide rolling rate — lows in last 5 m.'
    )
    pct_change: Optional[float] = None
    sell_pct_5m: Optional[float] = Field(
        None,
        description='5-minute aggressive-sell share (0–100). Present only on `market_summary`.',
    )
    session_high: Optional[float] = None
    session_low: Optional[float] = None
    symbol: str
    top_imbalance: Optional[float] = Field(
        None,
        description='L1 top-of-book imbalance `(bidSize − askSize) / (bidSize + askSize)`.',
    )
    trade_side: Optional[Literal['buy', 'sell', 'unknown']] = Field(
        None,
        description='Aggressor on the print that accompanied this transition (`buy` / `sell` / `unknown`).',
    )
    ts: str = Field(..., description='ISO-8601 UTC timestamp (millisecond precision).')
    type: Optional[str] = Field(
        'TAPE_EVENT',
        description='Constant `"TAPE_EVENT"` — lets generic JSON consumers dispatch without inspecting the full payload shape. Constructors set this via [`TapeEvent::new`]; deserialization defaults to the same constant so round-trips succeed without carrying the literal in a borrowed string.',
    )
    volume: Optional[float] = None
    volume_spike: bool


class HighlowtickerAlgoFeedWireProtocol(BaseModel):
    egress: Optional[TapeEvent] = None
    ingress: Optional[AlgoEvent] = None
